spring:
  config:
    import:
      - 'optional:file:.env[.properties]'
  cloud:
    config:
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: tickatch1211
    password: gjkxaxarpfacsvuz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

sms:
  api:
    key: ${SMS_API_KEY}
    secret: ${SMS_API_SECRET}
    domain: ${SMS_API_DOMAIN}
  send:
    from: ${SMS_SEND_FROM}